services:
  - type: web
    name: karmasetu-lms
    env: node
    plan: starter
    region: ohio
    branch: main
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    healthCheckPath: /api/health
    
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DB_NAME
        sync: false
      - key: SARVAM_API_KEY
        sync: false
      - key: MONGODB_SETUP_KEY
        sync: false
      - key: NEXT_PUBLIC_BASE_URL
        value: https://karmasetu-lms.onrender.com
      - key: NEXT_PUBLIC_PULSE_URL
        value: wss://karmasetu-lms.onrender.com/api/pulse
      - key: NODE_ENV
        value: production
        
    numInstances: 1
    autoDeploy: true