'use client';

import React, { createContext, useCallback, useContext, useState } from 'react';

type Lang = 'EN' | 'HINGLISH';

const translations: Record<Lang, Record<string, string>> = {
  EN: {
    // Admin Dashboard
    'admin.dashboard.title': 'Training Overview',
    'admin.dashboard.subtitle': 'KarmaSetu AI-Integrated Industrial Training Platform · Be Safe · Be Skilled · Be Productive',
    'admin.dashboard.feedback_inbox': 'Feedback Inbox',
    'admin.dashboard.feedback_desc': 'Review new trainee feedback and pending actions',
    'admin.dashboard.all_events': 'All Events',
    'admin.dashboard.pending_feedback': 'Pending Feedback',
    'admin.layout.verifying_access': 'Verifying admin access...',
    'admin.layout.redirecting_login': 'Redirecting to login...',
    'admin.profile.title': 'My Profile',
    'admin.profile.subtitle': 'HR Manager · Administration',
    'admin.compliance.title': 'Compliance Overview',
    'admin.compliance.subtitle': 'Factory-wide safety compliance and drill tracking',
    'admin.reports.title': 'Reports and Analytics',
    'admin.reports.subtitle': 'Live platform compliance and activity intelligence',
    'admin.courses.title': 'Course Management',
    'admin.courses.new_course': 'New Course',
    'admin.certificates.title': 'Certificate Management',
    'admin.certificates.issued_suffix': 'certificates issued',
    'admin.certificates.exporting': 'Exporting certificates...',
    'admin.certificates.export_csv': 'Export CSV',
    'admin.certificates.kpi.valid': 'VALID',
    'admin.certificates.kpi.expired': 'EXPIRED',
    'admin.certificates.kpi.revoked': 'REVOKED',
    'admin.certificates.filters_sorting': 'Certificate Filters and Sorting',
    'admin.certificates.reset': 'Reset',
    'admin.certificates.search_placeholder': 'Search cert #, trainee, course...',
    'admin.certificates.filter.all': 'All',
    'admin.certificates.filter.valid': 'Valid',
    'admin.certificates.filter.expired': 'Expired',
    'admin.certificates.filter.revoked': 'Revoked',
    'admin.settings.title': 'System Settings',
    'admin.settings.subtitle': 'Configure platform-wide settings, compliance thresholds, and notification preferences',
    'admin.settings.saving': 'Saving...',
    'admin.settings.save_changes': 'Save Changes',
    'admin.settings.saved_success': 'Settings saved successfully!',
    'admin.settings.section.general': 'General',
    'admin.settings.section.compliance': 'Compliance',
    'admin.settings.section.notifications': 'Notifications',
    'admin.settings.section.roles_defaults': 'Roles and Defaults',
    'admin.announcements.title': 'Announcements',
    'admin.announcements.subtitle': 'Send platform-wide alerts and notices to trainees',
    'admin.announcements.new_announcement': 'New Announcement',
    'admin.announcements.hidden_old_count_suffix': 'old announcement(s) are hidden by admin retention preference.',
    'admin.announcements.kpi.total_active': 'TOTAL ACTIVE',
    'admin.announcements.kpi.recent_7d': 'RECENT (7D)',
    'admin.announcements.kpi.audience_reached': 'AUDIENCE REACHED',
    'admin.announcements.filter.all': 'All',
    'admin.announcements.filter.recent': 'Recent',
    'admin.announcements.filter.high': 'High',
    'admin.announcements.filter.info': 'Info',
    'admin.announcements.filter.reminder': 'Reminder',
    'admin.announcements.filter.urgent': 'Urgent',
    'admin.announcements.deleted': 'Announcement deleted',
    'admin.announcements.empty': 'No announcements available for this filter.',
    'admin.announcements.title_placeholder': 'Announcement title',
    'admin.announcements.priority': 'Priority',
    'admin.announcements.message_placeholder': 'Write your announcement message...',
    'admin.announcements.message': 'Announcement message',
    'admin.announcements.send_to': 'Send To',
    'admin.announcements.all_departments': 'All Departments',
    'admin.announcements.send_now': 'Send Now',
    'admin.announcements.schedule_later': 'Schedule for Later',
    'admin.announcements.untitled': 'Untitled Announcement',
    'admin.announcements.no_message': 'No message provided.',
    'admin.announcements.sent_to': 'Announcement sent to',
    'admin.announcements.all_short': 'all',
    'admin.announcements.departments_suffix': 'departments!',
    'admin.announcements.send_announcement': 'Send Announcement',
    'admin.announcements.retention_prompt_prefix': 'announcement(s) are older than',
    'admin.announcements.retention_prompt_suffix': 'days. Choose retention action for this cycle.',
    'admin.announcements.retention_kept': 'Old announcements retained for this 15-day cycle.',
    'admin.announcements.retention_hidden': 'Old announcements hidden from dashboard for this cycle.',
    'admin.announcements.retention_removed': 'Old announcements removed from current dataset. Connect announcements API for DB deletion.',
    'admin.announcements.keep_old': 'Keep Old Announcements',
    'admin.announcements.hide_old': 'Hide Old Announcements',
    'admin.announcements.remove_old': 'Remove Old Announcements',
    'admin.announcements.sent_to_label': 'Sent to:',
    'admin.announcements.edit': 'Edit announcement',
    'admin.announcements.delete': 'Delete announcement',
    'admin.announcements.toggle_schedule': 'Toggle schedule',
    'admin.announcements.scheduled_datetime': 'Scheduled date and time',
    'admin.error.title': 'Admin Panel Error',
    'admin.error.subtitle': 'Something went wrong while loading this page.',
    'admin.error.try_again': 'Try Again',
    'admin.error.dashboard': 'Dashboard',
    'admin.modal.close': 'Close modal',
    'admin.overview.dept_compliance': 'Department Training Compliance',
    'admin.overview.no_dept_data': 'No department data available yet.',
    'admin.profile.edit_profile': 'Edit Profile',
    'admin.profile.full_name': 'Full Name',
    'admin.profile.job_title': 'Job Title',
    'admin.profile.select_department': 'Select department',
    'admin.profile.save_changes': 'Save Changes',
    'admin.profile.cancel': 'Cancel',
    'admin.profile.toast_updated': 'Profile updated successfully!',
    'admin.profile.change_password': 'Change Password',
    'admin.profile.password.current': 'Current Password',
    'admin.profile.password.new': 'New Password',
    'admin.profile.password.confirm': 'Confirm New Password',
    'admin.profile.password.update': 'Update Password',
    'admin.profile.password.very_strong': 'Very Strong',
    'admin.profile.password.strong': 'Strong',
    'admin.profile.password.fair': 'Fair',
    'admin.profile.password.weak': 'Weak',
    'admin.profile.toast_password_updated': 'Password updated successfully!',
    'admin.profile.badge.admin': 'ADMIN',
    'admin.profile.badge.management': 'Management',
    'admin.profile.stat.trainees_managed': 'Trainees Managed',
    'admin.profile.stat.certs_issued': 'Certs Issued',
    'admin.profile.stat.active_courses': 'Active Courses',
    'admin.profile.stat.admin_role_value': 'Admin',
    'admin.profile.stat.role': 'Role',
    'admin.profile.stat.full_access': 'Full platform access',
    'admin.profile.activity.course_created': 'Created new course "Leadership and Safety SOPs"',
    'admin.profile.activity.cert_issued': 'Issued certificate to Anjali Singh',
    'admin.profile.activity.announcement_sent': 'Sent announcement "Fire Drill Scheduled" to all departments',
    'admin.profile.activity.trainee_added': 'Added new trainee: Neha Gupta (HR and Admin)',
    'admin.profile.activity.time_2d': '2 days ago',
    'admin.profile.activity.time_3d': '3 days ago',
    'admin.profile.activity.time_mar12': 'Mar 12',
    'admin.profile.activity.time_mar10': 'Mar 10',
    'admin.profile.view_activity_log': 'View Full Activity Log →',
    'admin.sidebar.group.main': 'Main',
    'admin.sidebar.overview': 'Overview',
    'admin.sidebar.users': 'Users',
    'admin.sidebar.courses': 'Courses',
    'admin.sidebar.certificates': 'Certificates',
    'admin.sidebar.compliance': 'Compliance',
    'admin.sidebar.feedback': 'Feedback',
    'admin.sidebar.announcements': 'Announcements',
    'admin.sidebar.reports': 'Reports',
    'admin.sidebar.profile': 'Profile',
    'admin.sidebar.close_menu': 'Close menu',
    'admin.sidebar.buddy_assistant': 'Buddy AI Assistant',
    'admin.topbar.open_menu': 'Open menu',
    'admin.topbar.toggle_sidebar': 'Toggle sidebar',
    'admin.topbar.expand_sidebar_shortcut': 'Expand Sidebar (Alt+B)',
    'admin.topbar.collapse_sidebar_shortcut': 'Collapse Sidebar (Alt+B)',
    'admin.topbar.search_placeholder': 'Search telemetry, trainees, compliance records...',
    'admin.topbar.switch_to_hinglish': 'Switch language to Hinglish',
    'admin.topbar.switch_to_english': 'Switch language to English',
    'admin.topbar.open_notifications': 'Open notifications',
    'admin.topbar.notifications': 'Notifications',
    'admin.topbar.mark_all_read': 'Mark all read',
    'admin.topbar.compliance_alert_title': 'Compliance Alert',
    'admin.topbar.compliance_alert_body': '3 trainees from Manufacturing missed the deadline for Forklift Safety.',
    'admin.topbar.one_hour_ago': '1 hour ago',
    'admin.topbar.close_notifications_panel': 'Close notifications panel',
    'admin.topbar.view_all_alerts': 'View All Alerts',
    'admin.kpi.total_trainees': 'TOTAL TRAINEES',
    'admin.kpi.overdue': 'overdue',
    'admin.kpi.compliance': 'TRAINING COMPLIANCE',
    'admin.kpi.needs_attention': 'Needs Attention',
    'admin.kpi.good_standing': 'Good Standing',
    'admin.kpi.active_courses': 'ACTIVE COURSES',
    'admin.kpi.total_courses': 'total courses',
    'admin.kpi.valid_certificates': 'VALID CERTIFICATES',
    'admin.kpi.verified_registry': 'Verified in Registry',
    // Admin Overview
    'admin.overview.recent_activity': 'Recent Activity',
    'admin.overview.no_activity': 'No recent activity found.',
    'admin.overview.view_all_activity': 'View All Activity →',
    'admin.overview.alerts': 'Alerts',
    'admin.overview.dismiss_alert': 'Dismiss alert',
    'admin.overview.course_completion': 'Course Completion Rates',
    'admin.overview.pass_rate': 'Pass Rate',
    'admin.overview.trainee_status': 'Trainee Status Distribution',
    'admin.overview.trainees': 'Trainees',
    'admin.users.title': 'User Management',
    'admin.users.btn_add': 'Add User',
    'admin.users.table_trainee': 'Trainee',
    'admin.users.table_dept': 'Department',
    'admin.courses.subtitle_total_enrollments': 'total enrollments',
    'admin.feedback.title': 'Trainee Feedback',
    'admin.feedback.subtitle': 'Review suggestions and issues submitted by trainees',
    'admin.feedback.access_denied_redirect': 'Admin access denied. Redirecting to trainee dashboard...',
    'admin.feedback.filter_status': 'Status',
    'admin.feedback.filter_category': 'Category',
    'admin.feedback.filter_date': 'Date',
    'admin.feedback.filter_rating': 'Rating',
    'admin.feedback.option_all': 'All',
    'admin.feedback.status_open': 'Open',
    'admin.feedback.status_reviewing': 'Reviewing',
    'admin.feedback.status_resolved': 'Resolved',
    'admin.feedback.category_suggestion': 'Suggestion',
    'admin.feedback.category_issue': 'Issue',
    'admin.feedback.category_feature': 'Feature',
    'admin.feedback.category_general': 'General',
    'admin.feedback.date_all_time': 'All Time',
    'admin.feedback.date_7d': 'Last 7 Days',
    'admin.feedback.date_30d': 'Last 30 Days',
    'admin.feedback.date_90d': 'Last 90 Days',
    'admin.feedback.rating_any': 'Any',
    'admin.feedback.rating_unrated': 'Unrated',
    'admin.feedback.rating_5_only': '5 only',
    'admin.feedback.loading': 'Loading feedback...',
    'admin.feedback.table_trainee': 'Trainee',
    'admin.feedback.table_category': 'Category',
    'admin.feedback.table_message': 'Message',
    'admin.feedback.table_rating': 'Rating',
    'admin.feedback.table_status': 'Status',
    'admin.feedback.table_created': 'Created',
    'admin.feedback.table_resolution_context': 'Resolution Context',
    'admin.feedback.table_actions': 'Actions',
    'admin.feedback.placeholder_add_context': 'Add context before resolving',
    'admin.feedback.saved_prefix': 'Saved:',
    'admin.feedback.action_resolve': 'Resolve',
    'admin.feedback.min_note_hint': 'Add at least 5 chars note to resolve.',
    'admin.feedback.no_rows': 'No feedback rows match current filters.',
    'trainee.feedback.page_title': 'Feedback & Suggestions',
    'trainee.feedback.page_subtitle': 'Share issues, ideas, or feature requests. Admin team can review and resolve them.',
    'trainee.feedback.submit_title': 'Submit Feedback',
    'trainee.feedback.label_category': 'Category',
    'trainee.feedback.label_rating': 'Experience Rating',
    'trainee.feedback.rate_prefix': 'Rate',
    'trainee.feedback.label_message': 'Message',
    'trainee.feedback.placeholder_message': 'Tell us what should improve in training, dashboard, or learning experience...',
    'trainee.feedback.btn_submit': 'Submit Feedback',
    'trainee.feedback.btn_submitting': 'Submitting...',
    'trainee.feedback.history_title': 'My Feedback History',
    'trainee.feedback.loading': 'Loading feedback...',
    'trainee.feedback.empty': 'No feedback submitted yet.',
    'trainee.feedback.admin_note': 'Admin note',
    'trainee.feedback.notice_submitted': 'Feedback submitted. Thank you for helping improve KarmaSetu.',
    'trainee.feedback.toast_success': 'Feedback submitted successfully.',
    'trainee.feedback.error_load': 'Failed to load feedback.',
    'trainee.feedback.error_auth': 'Session expired. Redirecting to login...',
    'trainee.feedback.error_submit': 'Failed to submit feedback.',
    'trainee.feedback.error_retry': 'Failed to submit. Please try again.',
    'trainee.feedback.error_min_length': 'Please write at least 10 characters so admins can act on it.',
    'player.exit': 'Exit',
    'player.tab.lessons': 'Lessons',
    'player.tab.material': 'Material',
    'player.tab.quiz': 'Quiz',
    'player.material_locked': 'Material Locked',
    'player.view_doc': 'View Document',
    'player.quiz_locked': 'Quiz Locked',
    'player.retake_quiz': 'Retake Quiz',
    'player.start_quiz': 'Start Competency Check',


    'greeting.good_morning': 'Good Morning',
    'greeting.good_afternoon': 'Good Afternoon',
    'greeting.good_evening': 'Good Evening',

    'dashboard.title': 'Dashboard',
    'dashboard.welcome': 'Welcome',
    'dashboard.subtitle': 'Please review the safety protocols before starting chemical handling.',
    'dashboard.streak': 'day streak - keep going!',
    'dashboard.resume_title': 'Resume where you left off',
    'dashboard.start_title': 'Start your next lesson',
    'dashboard.completed': 'completed',
    'dashboard.resume_btn': 'Resume Training',
    'dashboard.start_btn': 'Start Course',
    'dashboard.kpi.overdue': 'Below the 80% target',
    'dashboard.quick_actions.ai': 'Ask AI Assistant',
    'dashboard.quick_actions.browse': 'Browse Courses',
    'dashboard.quick_actions.leaderboard': 'Leaderboard',
    'dashboard.courses.active_count': 'Active Modules',
    'dashboard.courses.assigned_count': 'New Assignments',
    'dashboard.courses.blocks': 'blocks',
    'dashboard.courses.no_active': 'No active courses yet. Start a new module below.',
    'dashboard.courses.enroll_btn': 'Enroll and Start',
    'dashboard.kpi.completed_suffix': 'completed',
    'dashboard.kpi.certificates_suffix': 'certificates',
    'dashboard.achievements_unlocked': 'achievements unlocked',

    'kpi.mandatory_training': 'MANDATORY TRAINING',
    'kpi.completed_courses': 'COMPLETED COURSES',
    'kpi.study_time': 'TOTAL STUDY TIME',
    'kpi.safety_alerts': 'SAFETY ALERTS',
    'kpi.certificates_earned': 'Certificates Earned',
    'kpi.hours': 'hours',
    'kpi.course': 'courses',
    'kpi.warnings': 'warnings',

    'courses.active': 'My Active Courses',
    'courses.view_all': 'View All ->',
    'courses.continue': 'CONTINUE',
    'courses.start': 'START',

    'events.title': 'Upcoming Events',
    'achievements.title': 'Achievements',
    'tip.label': 'DAILY SAFETY TIP',
    'tip.safety_1': 'Do not start any chemical handling task until the label and SDS have been verified.',
    'tip.safety_2': 'Always wear PPE before entering the production floor.',
    'tip.safety_3': 'Check the location and type of the fire extinguisher before every shift.',
    'tip.safety_4': 'Never bypass the LOTO procedure.',
    'tip.safety_5': 'Report every near-miss incident because small hazards prevent major accidents.',
    'tip.safety_6': 'Use insulated gloves when working near electrical panels.',
    'tip.safety_7': 'Good housekeeping prevents most workplace accidents.',
    'tip.safety_8': 'Memorize emergency exit routes and never block them.',
    'tip.safety_9': 'Take hydration breaks because fatigue increases risk.',
    'tip.safety_10': 'Safety is everyone\'s responsibility, so speak up when you see a hazard.',

    'nav.dashboard': 'Dashboard',
    'nav.training': 'Training',
    'nav.practice_quiz': 'Practice Quiz',
    'nav.certificates': 'Certificates',
    'nav.leaderboard': 'Leaderboard',
    'nav.feedback': 'Feedback',
    'nav.profile': 'Profile',
    'nav.settings': 'AI Settings',
    'nav.logout': 'Logout',
    'nav.role.trainee': 'Trainee',
    'nav.search_placeholder': 'Search courses, SOPs, skills...',
    'nav.features': 'Features',
    'nav.domains': 'Domains',
    'nav.blog': 'Blog',
    'nav.faq': 'FAQ',
    'nav.open': 'Open',
    'nav.signin': 'Sign In',
    'nav.get_started': 'Get Started',
    'nav.logo_tagline': 'AI Integrated Industrial Training Portal',

    'login.title': 'Login',
    'login.subtitle': 'Welcome to KarmaSetu',
    'login.email': 'Email',
    'login.password': 'Password',
    'login.submit': 'Continue',
    'login.google': 'Login with Google',

    'training.title': 'Training Hub',
    'training.subtitle': 'Manage your active training and enroll in new assignments',
    'training.modules.active': 'Active Modules',
    'training.modules.assigned': 'New Assignments',
    'training.modules.completed': 'Completed',
    'training.action.review': 'Review Modules',
    'training.action.resume': 'Resume Training',
    'training.action.enroll': 'Enroll and Start Course',
    'training.viewer.ready': 'Ready to Start?',
    'training.viewer.review': 'Review Knowledge',
    'training.viewer.active': 'Active Training',
    'training.viewer.desc_start': 'Enroll now to access industrial safety videos, official documentation, and the final assessment.',
    'training.viewer.desc_continue': 'Return to your learning space and continue your progress toward certification.',

    'hero.badge': 'AI-Powered Industrial Training',
    'hero.word1': 'Train',
    'hero.word2': 'Smarter.',
    'hero.word3': 'Work',
    'hero.word4': 'Safer.',
    'hero.description': 'India\'s AI-integrated industrial training platform. From chemical safety to machine operations, build every skill with AI-powered learning, smart quizzes, and digital certificates.',
    'hero.start_training': 'Start Training Free',
    'hero.sign_in': 'Sign In ->',
    'hero.trust': 'No credit card required | Free to start | Made in India',
    'hero.stats.courses': '15+ Training Courses',
    'hero.stats.quizzes': 'AI Powered Quizzes',
    'hero.stats.assistant': '24/7 AI Assistant',
    'hero.stats.trainees': '500+ Certified Trainees',

    'stats.training_courses': 'Training Courses',
    'stats.certified_trainees': 'Certified Trainees',
    'stats.avg_ai_quiz_score': 'Avg. AI Quiz Score',
    'stats.ai_assistant': 'AI Assistant',
    'stats.mandatory': 'Target Compliance',
    'stats.mandatory_desc': 'Below the 80% target',
    'stats.completed': 'Completed Modules',
    'stats.completed_desc': '1 module to go',
    'stats.study_time': 'Study Hours',
    'stats.study_hours_unit': 'h',
    'stats.study_time_desc': 'Top 10% this week',
    'stats.safety_alerts': 'Active Alerts',
    'stats.safety_alerts_desc': 'Action required',
    'badges.title': 'Badges & Achievements',

    'certs.page_title': 'Academic & Training Records',
    'certs.page_subtitle': 'Access your officially recognized industrial safety certifications',
    'certs.search_placeholder': 'Search by course or ID...',
    'certs.filter_all': 'All Status',
    'certs.filter_valid': 'Valid',
    'certs.filter_expired': 'Expired',
    'certs.filter_revoked': 'Revoked',
    'certs.loading': 'Loading certificates...',
    'certs.empty_title': 'No Certifications Yet',
    'certs.empty_desc': 'You have not completed any training assessments yet. Complete a course to earn your first industrial safety certificate.',
    'certs.browse': 'Browse Courses',
    'certs.action_view': 'View',
    'certs.action_pdf': 'PDF',
    'certs.action_share': 'Share',
    'certs.share_linkedin': 'LinkedIn',
    'certs.share_whatsapp': 'WhatsApp',
    'certs.share_x': 'X (Twitter)',
    'certs.issued': 'Issued',
    'certs.expires': 'Expires',
    'certs.next_unlock': 'Next Unlock',
    'certs.next_unlock_desc': 'Complete your active modules to earn more certifications',

    'features.badge': 'PLATFORM FEATURES',
    'features.title_prefix': 'Everything You Need to',
    'features.title_highlight': 'Upskill Your Workforce',
    'feature.chatbot.title': 'AI Chatbot',
    'feature.chatbot.description': 'Get instant answers on safety, SOPs, and compliance from an AI assistant that is available 24/7.',
    'feature.quiz.title': 'AI Quiz Generator',
    'feature.quiz.description': 'Create quizzes for every training module with adaptive difficulty and automatic scoring.',
    'feature.training.title': 'Interactive Training',
    'feature.training.description': 'Deliver structured industrial training with video lessons, PDF study material, and clear learning paths.',
    'feature.certificate.title': 'Smart Certificates',
    'feature.certificate.description': 'Generate digital certificates automatically with unique QR codes after course completion.',
    'feature.analytics.title': 'Live Analytics',
    'feature.analytics.description': 'Track compliance scores, course completion, and department performance in real time.',
    'feature.admin.title': 'Admin Dashboard',
    'feature.admin.description': 'Manage onboarding, course assignments, compliance tracking, and report exports from one place.',

    'domains.badge': 'TRAINING DOMAINS',
    'domains.title': 'Comprehensive Industrial Coverage',
    'domains.description': 'From chemical safety to machine operations, cover every domain your workforce needs to stay safe and compliant.',
    'domains.course_single': 'Course',
    'domains.course_plural': 'Courses',
    'domains.explore': 'Explore Courses ->',
    'domain.health-safety': 'Health and Safety',
    'domain.machine-ops': 'Machine Operations',
    'domain.quality-compliance': 'Quality and Compliance',
    'domain.chemical-handling': 'Chemical Handling',
    'domain.electrical-safety': 'Electrical Safety',
    'domain.leadership-sops': 'Leadership and SOPs',

    'faq.badge': 'FAQ',
    'faq.title': 'Frequently Asked Questions',
    'faq.subtitle': 'Everything you should know before getting started',
    'faq.q1': 'Is the platform free to use?',
    'faq.a1': 'Yes. The platform includes a free tier with access to core training courses, AI quizzes, and basic certificates. Advanced organizational features are available on higher plans. No credit card is required to begin.',
    'faq.q2': 'What industries and domains does this platform cover?',
    'faq.a2': 'The platform covers Health and Safety, Machine Operations, Quality and Compliance, Chemical Handling, Electrical Safety, and Leadership and SOPs for industrial and manufacturing environments in India.',
    'faq.q3': 'How are certificates generated after course completion?',
    'faq.a3': 'A passing quiz score and completed course trigger an automatic digital certificate with a unique ID, QR verification, trainee name, course name, score, and completion date.',
    'faq.q4': 'Is the platform mobile-friendly for factory floor workers?',
    'faq.a4': 'Yes. The platform is fully responsive on mobile, tablet, and desktop so workers can learn, take quizzes, and view certificates from any device.',
    'faq.q5': 'How does the AI chatbot work?',
    'faq.a5': 'Buddy AI is trained on industrial safety protocols, SOPs, and best practices. Workers can ask questions and receive instant guidance in English or Hinglish.',
    'faq.q6': 'Can I use KarmaSetu for my entire organization?',
    'faq.a6': 'Yes. Enterprise plans include admin dashboards, workforce progress tracking, compliance reporting, custom courses, and dedicated support.',
    'faq.q7': 'What languages are supported?',
    'faq.a7': 'KarmaSetu supports English and Hinglish across the learning platform and Buddy AI assistant.',

    'blog.badge': 'FROM THE BLOG',
    'blog.title_prefix': 'Latest',
    'blog.title_highlight': 'Insights',
    'blog.view_all': 'View All Articles ->',

    'cta.title_prefix': 'Ready to Transform Your',
    'cta.title_highlight': 'Safety Training?',
    'cta.description': 'Join industries across India that are upgrading workforce training with KarmaSetu\'s AI-powered platform.',
    'cta.primary': 'Get Started for Free',
    'cta.secondary': 'Explore Features ->',
    'cta.trust': 'Free forever plan | No credit card required | Setup in 5 minutes',

    'landing.mascot.label': 'Buddy AI',
    'landing.mascot.body': 'Ready to master industrial safety? I will guide you through the courses step by step.',
    'landing.mascot.cta': 'Sign In to Start Training',
  },
  HINGLISH: {
    // Admin Dashboard
    'admin.dashboard.title': 'Training Overview',
    'admin.dashboard.subtitle': 'KarmaSetu AI-Integrated Industrial Training Platform · Safe रहें · Skilled बनें · Productive रहें',
    'admin.dashboard.feedback_inbox': 'Feedback Inbox',
    'admin.dashboard.feedback_desc': 'नई trainee feedback और pending actions की समीक्षा करें',
    'admin.dashboard.all_events': 'All Events',
    'admin.dashboard.pending_feedback': 'Pending Feedback',
    'admin.layout.verifying_access': 'एडमिन एक्सेस verify किया जा रहा है...',
    'admin.layout.redirecting_login': 'लॉगिन पर redirect किया जा रहा है...',
    'admin.profile.title': 'मेरा प्रोफाइल',
    'admin.profile.subtitle': 'HR Manager · Administration',
    'admin.compliance.title': 'कंप्लायंस ओवरव्यू',
    'admin.compliance.subtitle': 'फैक्ट्री-लेवल safety compliance और drill tracking',
    'admin.reports.title': 'रिपोर्ट्स और एनालिटिक्स',
    'admin.reports.subtitle': 'Live platform compliance और activity intelligence',
    'admin.courses.title': 'कोर्स मैनेजमेंट',
    'admin.courses.new_course': 'नया कोर्स',
    'admin.certificates.title': 'सर्टिफिकेट मैनेजमेंट',
    'admin.certificates.issued_suffix': 'सर्टिफिकेट जारी',
    'admin.certificates.exporting': 'सर्टिफिकेट export हो रहे हैं...',
    'admin.certificates.export_csv': 'CSV Export',
    'admin.certificates.kpi.valid': 'VALID',
    'admin.certificates.kpi.expired': 'EXPIRED',
    'admin.certificates.kpi.revoked': 'REVOKED',
    'admin.certificates.filters_sorting': 'सर्टिफिकेट फिल्टर्स और सॉर्टिंग',
    'admin.certificates.reset': 'रीसेट',
    'admin.certificates.search_placeholder': 'Cert #, trainee, course खोजें...',
    'admin.certificates.filter.all': 'सभी',
    'admin.certificates.filter.valid': 'Valid',
    'admin.certificates.filter.expired': 'Expired',
    'admin.certificates.filter.revoked': 'Revoked',
    'admin.settings.title': 'सिस्टम सेटिंग्स',
    'admin.settings.subtitle': 'Platform-wide settings, compliance threshold और notification preferences configure करें',
    'admin.settings.saving': 'सेव हो रहा है...',
    'admin.settings.save_changes': 'बदलाव सेव करें',
    'admin.settings.saved_success': 'सेटिंग्स सफलतापूर्वक सेव हुईं!',
    'admin.settings.section.general': 'जनरल',
    'admin.settings.section.compliance': 'कंप्लायंस',
    'admin.settings.section.notifications': 'नोटिफिकेशन्स',
    'admin.settings.section.roles_defaults': 'Roles और Defaults',
    'admin.announcements.title': 'घोषणाएं',
    'admin.announcements.subtitle': 'Trainees के लिए platform-wide alerts और notices भेजें',
    'admin.announcements.new_announcement': 'नई घोषणा',
    'admin.announcements.hidden_old_count_suffix': 'पुरानी announcement(s) admin retention preference से छिपी हैं।',
    'admin.announcements.kpi.total_active': 'TOTAL ACTIVE',
    'admin.announcements.kpi.recent_7d': 'RECENT (7D)',
    'admin.announcements.kpi.audience_reached': 'AUDIENCE REACHED',
    'admin.announcements.filter.all': 'सभी',
    'admin.announcements.filter.recent': 'हाल की',
    'admin.announcements.filter.high': 'High',
    'admin.announcements.filter.info': 'Info',
    'admin.announcements.filter.reminder': 'Reminder',
    'admin.announcements.filter.urgent': 'Urgent',
    'admin.announcements.deleted': 'घोषणा delete कर दी गई',
    'admin.announcements.empty': 'इस filter के लिए कोई announcement उपलब्ध नहीं है।',
    'admin.announcements.title_placeholder': 'घोषणा शीर्षक',
    'admin.announcements.priority': 'प्राथमिकता',
    'admin.announcements.message_placeholder': 'अपना announcement message लिखें...',
    'admin.announcements.message': 'घोषणा संदेश',
    'admin.announcements.send_to': 'किसे भेजें',
    'admin.announcements.all_departments': 'सभी विभाग',
    'admin.announcements.send_now': 'अभी भेजें',
    'admin.announcements.schedule_later': 'बाद में शेड्यूल करें',
    'admin.announcements.untitled': 'बिना शीर्षक घोषणा',
    'admin.announcements.no_message': 'कोई संदेश नहीं दिया गया।',
    'admin.announcements.sent_to': 'घोषणा भेजी गई',
    'admin.announcements.all_short': 'सभी',
    'admin.announcements.departments_suffix': 'विभागों को!',
    'admin.announcements.send_announcement': 'घोषणा भेजें',
    'admin.announcements.retention_prompt_prefix': 'announcement(s) इससे पुरानी हैं',
    'admin.announcements.retention_prompt_suffix': 'दिन. इस cycle के लिए retention action चुनें।',
    'admin.announcements.retention_kept': 'पुरानी announcements इस 15-दिन cycle के लिए रखी गई हैं।',
    'admin.announcements.retention_hidden': 'पुरानी announcements इस cycle के लिए dashboard से छिपा दी गई हैं।',
    'admin.announcements.retention_removed': 'पुरानी announcements current dataset से हटाई गई हैं। DB deletion के लिए announcements API जोड़ें।',
    'admin.announcements.keep_old': 'पुरानी घोषणाएं रखें',
    'admin.announcements.hide_old': 'पुरानी घोषणाएं छिपाएं',
    'admin.announcements.remove_old': 'पुरानी घोषणाएं हटाएं',
    'admin.announcements.sent_to_label': 'किसे भेजा गया:',
    'admin.announcements.edit': 'घोषणा संपादित करें',
    'admin.announcements.delete': 'घोषणा हटाएं',
    'admin.announcements.toggle_schedule': 'शेड्यूल टॉगल करें',
    'admin.announcements.scheduled_datetime': 'निर्धारित दिनांक और समय',
    'admin.error.title': 'एडमिन पैनल त्रुटि',
    'admin.error.subtitle': 'यह पेज लोड करते समय कुछ गलत हो गया।',
    'admin.error.try_again': 'फिर कोशिश करें',
    'admin.error.dashboard': 'डैशबोर्ड',
    'admin.modal.close': 'मोडल बंद करें',
    'admin.overview.dept_compliance': 'विभागीय ट्रेनिंग कंप्लायंस',
    'admin.overview.no_dept_data': 'अभी विभागीय डेटा उपलब्ध नहीं है।',
    'admin.profile.edit_profile': 'प्रोफाइल संपादित करें',
    'admin.profile.full_name': 'पूरा नाम',
    'admin.profile.job_title': 'जॉब टाइटल',
    'admin.profile.select_department': 'विभाग चुनें',
    'admin.profile.save_changes': 'बदलाव सेव करें',
    'admin.profile.cancel': 'रद्द करें',
    'admin.profile.toast_updated': 'प्रोफाइल सफलतापूर्वक अपडेट हुई!',
    'admin.profile.change_password': 'पासवर्ड बदलें',
    'admin.profile.password.current': 'वर्तमान पासवर्ड',
    'admin.profile.password.new': 'नया पासवर्ड',
    'admin.profile.password.confirm': 'नया पासवर्ड पुष्टि करें',
    'admin.profile.password.update': 'पासवर्ड अपडेट करें',
    'admin.profile.password.very_strong': 'बहुत मजबूत',
    'admin.profile.password.strong': 'मजबूत',
    'admin.profile.password.fair': 'ठीक-ठाक',
    'admin.profile.password.weak': 'कमजोर',
    'admin.profile.toast_password_updated': 'पासवर्ड सफलतापूर्वक अपडेट हुआ!',
    'admin.profile.badge.admin': 'ADMIN',
    'admin.profile.badge.management': 'Management',
    'admin.profile.stat.trainees_managed': 'ट्रेनी मैनेज किए',
    'admin.profile.stat.certs_issued': 'जारी सर्टिफिकेट्स',
    'admin.profile.stat.active_courses': 'सक्रिय कोर्सेज',
    'admin.profile.stat.admin_role_value': 'एडमिन',
    'admin.profile.stat.role': 'भूमिका',
    'admin.profile.stat.full_access': 'पूरे प्लेटफॉर्म का एक्सेस',
    'admin.profile.activity.course_created': 'नया कोर्स बनाया "Leadership and Safety SOPs"',
    'admin.profile.activity.cert_issued': 'Anjali Singh को सर्टिफिकेट जारी किया',
    'admin.profile.activity.announcement_sent': '"Fire Drill Scheduled" घोषणा सभी विभागों को भेजी',
    'admin.profile.activity.trainee_added': 'नया ट्रेनी जोड़ा: Neha Gupta (HR and Admin)',
    'admin.profile.activity.time_2d': '2 दिन पहले',
    'admin.profile.activity.time_3d': '3 दिन पहले',
    'admin.profile.activity.time_mar12': '12 मार्च',
    'admin.profile.activity.time_mar10': '10 मार्च',
    'admin.profile.view_activity_log': 'पूरा Activity Log देखें →',
    'admin.sidebar.group.main': 'मुख्य',
    'admin.sidebar.overview': 'ओवरव्यू',
    'admin.sidebar.users': 'यूजर्स',
    'admin.sidebar.courses': 'कोर्सेज',
    'admin.sidebar.certificates': 'सर्टिफिकेट्स',
    'admin.sidebar.compliance': 'कंप्लायंस',
    'admin.sidebar.feedback': 'फीडबैक',
    'admin.sidebar.announcements': 'घोषणाएं',
    'admin.sidebar.reports': 'रिपोर्ट्स',
    'admin.sidebar.profile': 'प्रोफाइल',
    'admin.sidebar.close_menu': 'मेनू बंद करें',
    'admin.sidebar.buddy_assistant': 'Buddy AI सहायक',
    'admin.topbar.open_menu': 'मेनू खोलें',
    'admin.topbar.toggle_sidebar': 'साइडबार टॉगल करें',
    'admin.topbar.expand_sidebar_shortcut': 'साइडबार फैलाएं (Alt+B)',
    'admin.topbar.collapse_sidebar_shortcut': 'साइडबार समेटें (Alt+B)',
    'admin.topbar.search_placeholder': 'टेलीमेट्री, ट्रेनी और कंप्लायंस रिकॉर्ड खोजें...',
    'admin.topbar.switch_to_hinglish': 'भाषा Hinglish में बदलें',
    'admin.topbar.switch_to_english': 'भाषा English में बदलें',
    'admin.topbar.open_notifications': 'नोटिफिकेशन खोलें',
    'admin.topbar.notifications': 'नोटिफिकेशन',
    'admin.topbar.mark_all_read': 'सभी को पढ़ा हुआ मार्क करें',
    'admin.topbar.compliance_alert_title': 'कंप्लायंस अलर्ट',
    'admin.topbar.compliance_alert_body': 'Manufacturing के 3 trainees ने Forklift Safety की समय-सीमा मिस कर दी।',
    'admin.topbar.one_hour_ago': '1 घंटा पहले',
    'admin.topbar.close_notifications_panel': 'नोटिफिकेशन पैनल बंद करें',
    'admin.topbar.view_all_alerts': 'सभी अलर्ट देखें',
    'admin.kpi.total_trainees': 'TOTAL TRAINEES',
    'admin.kpi.overdue': 'overdue हैं',
    'admin.kpi.compliance': 'TRAINING COMPLIANCE',
    'admin.kpi.needs_attention': 'Attention की जरूरत है',
    'admin.kpi.good_standing': 'Good Standing में हैं',
    'admin.kpi.active_courses': 'ACTIVE COURSES',
    'admin.kpi.total_courses': 'total courses',
    'admin.kpi.valid_certificates': 'VALID CERTIFICATES',
    'admin.kpi.verified_registry': 'Registry में Verified',
    // Admin Overview
    'admin.overview.recent_activity': 'Recent Activity',
    'admin.overview.no_activity': 'कोई recent activity नहीं मिली.',
    'admin.overview.view_all_activity': 'सभी Activity देखें →',
    'admin.overview.alerts': 'Alerts',
    'admin.overview.dismiss_alert': 'Alert हटाएं',
    'admin.overview.course_completion': 'Course Completion Rates',
    'admin.overview.pass_rate': 'Pass Rate',
    'admin.overview.trainee_status': 'Trainee Status Distribution',
    'admin.overview.trainees': 'Trainees',
    'admin.users.title': 'User Management',
    'admin.users.btn_add': 'User Add करें',
    'admin.users.table_trainee': 'ट्रेनी',
    'admin.users.table_dept': 'विभाग',
    'admin.courses.subtitle_total_enrollments': 'total enrollments',
    'admin.feedback.title': 'ट्रेनी फीडबैक',
    'admin.feedback.subtitle': 'ट्रेनी द्वारा भेजे गए सुझाव और समस्याओं की समीक्षा करें',
    'admin.feedback.access_denied_redirect': 'एडमिन एक्सेस नहीं है। ट्रेनी डैशबोर्ड पर भेजा जा रहा है...',
    'admin.feedback.filter_status': 'स्थिति',
    'admin.feedback.filter_category': 'श्रेणी',
    'admin.feedback.filter_date': 'तारीख',
    'admin.feedback.filter_rating': 'रेटिंग',
    'admin.feedback.option_all': 'सभी',
    'admin.feedback.status_open': 'खुला',
    'admin.feedback.status_reviewing': 'समीक्षा में',
    'admin.feedback.status_resolved': 'सुलझा',
    'admin.feedback.category_suggestion': 'सुझाव',
    'admin.feedback.category_issue': 'समस्या',
    'admin.feedback.category_feature': 'फीचर',
    'admin.feedback.category_general': 'सामान्य',
    'admin.feedback.date_all_time': 'पूरा समय',
    'admin.feedback.date_7d': 'पिछले 7 दिन',
    'admin.feedback.date_30d': 'पिछले 30 दिन',
    'admin.feedback.date_90d': 'पिछले 90 दिन',
    'admin.feedback.rating_any': 'कोई भी',
    'admin.feedback.rating_unrated': 'बिना रेटिंग',
    'admin.feedback.rating_5_only': 'सिर्फ 5',
    'admin.feedback.loading': 'Feedback load हो रहा है...',
    'admin.feedback.table_trainee': 'ट्रेनी',
    'admin.feedback.table_category': 'श्रेणी',
    'admin.feedback.table_message': 'संदेश',
    'admin.feedback.table_rating': 'रेटिंग',
    'admin.feedback.table_status': 'स्थिति',
    'admin.feedback.table_created': 'बनाया गया',
    'admin.feedback.table_resolution_context': 'समाधान संदर्भ',
    'admin.feedback.table_actions': 'कार्रवाई',
    'admin.feedback.placeholder_add_context': 'सुलझाने से पहले संदर्भ लिखें',
    'admin.feedback.saved_prefix': 'सहेजा गया:',
    'admin.feedback.action_resolve': 'सुलझाएं',
    'admin.feedback.min_note_hint': 'सुलझाने के लिए कम से कम 5 अक्षरों का नोट लिखें।',
    'admin.feedback.no_rows': 'मौजूदा फिल्टर के अनुसार कोई फीडबैक पंक्ति नहीं मिली।',
    'trainee.feedback.page_title': 'फीडबैक और सुझाव',
    'trainee.feedback.page_subtitle': 'समस्याएं, सुझाव या नए फीचर के अनुरोध साझा करें। एडमिन टीम इन्हें देखकर सुलझा सकती है।',
    'trainee.feedback.submit_title': 'फीडबैक भेजें',
    'trainee.feedback.label_category': 'श्रेणी',
    'trainee.feedback.label_rating': 'अनुभव रेटिंग',
    'trainee.feedback.rate_prefix': 'रेट करें',
    'trainee.feedback.label_message': 'संदेश',
    'trainee.feedback.placeholder_message': 'ट्रेनिंग, डैशबोर्ड या लर्निंग अनुभव में क्या बेहतर होना चाहिए, यहां लिखें...',
    'trainee.feedback.btn_submit': 'फीडबैक भेजें',
    'trainee.feedback.btn_submitting': 'भेजा जा रहा है...',
    'trainee.feedback.history_title': 'मेरा फीडबैक इतिहास',
    'trainee.feedback.loading': 'फीडबैक लोड हो रहा है...',
    'trainee.feedback.empty': 'अभी तक कोई फीडबैक जमा नहीं किया गया।',
    'trainee.feedback.admin_note': 'एडमिन नोट',
    'trainee.feedback.notice_submitted': 'फीडबैक जमा हो गया। KarmaSetu बेहतर बनाने में मदद के लिए धन्यवाद।',
    'trainee.feedback.toast_success': 'फीडबैक सफलतापूर्वक भेजा गया।',
    'trainee.feedback.error_load': 'फीडबैक लोड नहीं हो पाया।',
    'trainee.feedback.error_auth': 'सेशन समाप्त हो गया। लॉगिन पेज पर भेजा जा रहा है...',
    'trainee.feedback.error_submit': 'फीडबैक भेजा नहीं जा सका।',
    'trainee.feedback.error_retry': 'फीडबैक भेजा नहीं जा सका। कृपया फिर कोशिश करें।',
    'trainee.feedback.error_min_length': 'कृपया कम से कम 10 अक्षर लिखें ताकि एडमिन कार्रवाई कर सके।',
    'player.exit': 'बाहर जाएं',
    'player.tab.lessons': 'पाठ',
    'player.tab.material': 'सामग्री',
    'player.tab.quiz': 'क्विज',
    'player.material_locked': 'सामग्री लॉक है',
    'player.view_doc': 'दस्तावेज़ देखें',
    'player.quiz_locked': 'क्विज लॉक है',
    'player.retake_quiz': 'क्विज दोबारा दें',
    'player.start_quiz': 'कंपिटेंसी चेक शुरू करें',


    'greeting.good_morning': 'Good Morning',
    'greeting.good_afternoon': 'Good Afternoon',
    'greeting.good_evening': 'Good Evening',

    'dashboard.title': 'Dashboard',
    'dashboard.welcome': 'स्वागत है',
    'dashboard.subtitle': 'Chemical handling शुरू करने से पहले safety protocols check करें.',
    'dashboard.streak': 'दिन का streak - ऐसे ही जारी रखें!',
    'dashboard.resume_title': 'जहां छोड़ा था वहीं से continue करें',
    'dashboard.start_title': 'अगला lesson शुरू करें',
    'dashboard.completed': 'complete',
    'dashboard.resume_btn': 'Training Resume करें',
    'dashboard.start_btn': 'Course शुरू करें',
    'dashboard.kpi.overdue': '80% target से नीचे',
    'dashboard.quick_actions.ai': 'AI Assistant से पूछें',
    'dashboard.quick_actions.browse': 'Courses देखें',
    'dashboard.quick_actions.leaderboard': 'लीडरबोर्ड',
    'dashboard.courses.active_count': 'Active Modules',
    'dashboard.courses.assigned_count': 'नए Assignments',
    'dashboard.courses.blocks': 'blocks',
    'dashboard.courses.no_active': 'अभी कोई active course नहीं है. नीचे नया module शुरू करें.',
    'dashboard.courses.enroll_btn': 'Enroll करके Start करें',
    'dashboard.kpi.completed_suffix': 'complete',
    'dashboard.kpi.certificates_suffix': 'certificates',
    'dashboard.achievements_unlocked': 'achievements unlock हुए',

    'kpi.mandatory_training': 'जरूरी Training',
    'kpi.completed_courses': 'Complete किए Courses',
    'kpi.study_time': 'कुल Study Time',
    'kpi.safety_alerts': 'Safety Alerts',
    'kpi.certificates_earned': 'Earned Certificates',
    'kpi.hours': 'घंटे',
    'kpi.course': 'courses',
    'kpi.warnings': 'warnings',

    'courses.active': 'मेरे Active Courses',
    'courses.view_all': 'सभी देखें ->',
    'courses.continue': 'जारी रखें',
    'courses.start': 'शुरू करें',

    'events.title': 'आने वाले Events',
    'achievements.title': 'Achievements',
    'tip.label': 'आज की Safety Tip',
    'tip.safety_1': 'Chemical handling का काम label और SDS verify किए बिना शुरू मत करें.',
    'tip.safety_2': 'Production floor में जाने से पहले हमेशा PPE पहनें.',
    'tip.safety_3': 'हर shift से पहले fire extinguisher की location और type check करें.',
    'tip.safety_4': 'LOTO procedure को कभी bypass मत करें.',
    'tip.safety_5': 'हर near-miss incident report करें, क्योंकि छोटे hazards बड़े accidents रोकते हैं.',
    'tip.safety_6': 'Electrical panels के पास काम करते समय insulated gloves इस्तेमाल करें.',
    'tip.safety_7': 'साफ workplace ज़्यादातर accidents रोकता है.',
    'tip.safety_8': 'Emergency exit routes याद रखें और उन्हें कभी block मत करें.',
    'tip.safety_9': 'Hydration breaks लेते रहें, क्योंकि थकान risk बढ़ाती है.',
    'tip.safety_10': 'Safety सबकी responsibility है, इसलिए hazard दिखे तो तुरंत बोलें.',

    'nav.dashboard': 'डैशबोर्ड',
    'nav.training': 'ट्रेनिंग',
    'nav.practice_quiz': 'प्रैक्टिस क्विज़',
    'nav.certificates': 'सर्टिफिकेट्स',
    'nav.leaderboard': 'लीडरबोर्ड',
    'nav.feedback': 'फीडबैक',
    'nav.profile': 'प्रोफाइल',
    'nav.settings': 'AI सेटिंग्स',
    'nav.logout': 'लॉगआउट',
    'nav.role.trainee': 'ट्रेनी',
    'nav.search_placeholder': 'Courses, SOPs, skills search करें...',
    'nav.features': 'Features',
    'nav.domains': 'Domains',
    'nav.blog': 'Blog',
    'nav.faq': 'FAQ',
    'nav.open': 'Open',
    'nav.signin': 'Sign In',
    'nav.get_started': 'Get Started',
    'nav.logo_tagline': 'AI Integrated Industrial Training Portal',

    'login.title': 'Login',
    'login.subtitle': 'KarmaSetu में आपका स्वागत है',
    'login.email': 'Email',
    'login.password': 'Password',
    'login.submit': 'आगे बढ़ें',
    'login.google': 'Google के साथ Login करें',

    'training.title': 'Training Hub',
    'training.subtitle': 'अपनी active training manage करें और नए assignments में enroll करें',
    'training.modules.active': 'Active Modules',
    'training.modules.assigned': 'नए Assignments',
    'training.modules.completed': 'Complete',
    'training.action.review': 'Modules Review करें',
    'training.action.resume': 'Training Resume करें',
    'training.action.enroll': 'Enroll करके Course शुरू करें',
    'training.viewer.ready': 'शुरू करने के लिए ready हैं?',
    'training.viewer.review': 'Knowledge Review करें',
    'training.viewer.active': 'Active Training',
    'training.viewer.desc_start': 'Industrial safety videos, official documentation, और final assessment access करने के लिए अभी enroll करें.',
    'training.viewer.desc_continue': 'अपने learning space में वापस जाएं और certification की तरफ progress जारी रखें.',

    'hero.badge': 'AI-Powered Industrial Training',
    'hero.word1': 'Smart तरीके से',
    'hero.word2': 'Train करें.',
    'hero.word3': 'Safe तरीके से',
    'hero.word4': 'काम करें.',
    'hero.description': 'India का AI-integrated industrial training platform. Chemical safety से machine operations तक हर skill को AI-powered learning, smart quizzes, और digital certificates के साथ master करें.',
    'hero.start_training': 'Free Training शुरू करें',
    'hero.sign_in': 'Sign In करें ->',
    'hero.trust': 'Credit card की जरूरत नहीं | Free में start करें | Made in India',
    'hero.stats.courses': '15+ Training Courses',
    'hero.stats.quizzes': 'AI Powered Quizzes',
    'hero.stats.assistant': '24/7 AI Assistant',
    'hero.stats.trainees': '500+ Certified Trainees',

    'stats.training_courses': 'ट्रेनिंग कोर्सेज',
    'stats.certified_trainees': 'सर्टिफाइड ट्रेनीज',
    'stats.avg_ai_quiz_score': 'औसत AI क्विज़ स्कोर',
    'stats.ai_assistant': 'AI असिस्टेंट',
    'stats.mandatory': 'लक्ष्य अनुपालन',
    'stats.mandatory_desc': '80% लक्ष्य से नीचे',
    'stats.completed': 'पूरे किए गए मॉड्यूल',
    'stats.completed_desc': '1 मॉड्यूल बाकी है',
    'stats.study_time': 'स्टडी के घंटे',
    'stats.study_hours_unit': ' घंटे',
    'stats.study_time_desc': 'इस हफ्ते शीर्ष 10% में',
    'stats.safety_alerts': 'सक्रिय अलर्ट्स',
    'stats.safety_alerts_desc': 'कार्रवाई चाहिए',
    'badges.title': 'बैज और उपलब्धियां',

    'certs.page_title': 'उपलब्धि और Training Records',
    'certs.page_subtitle': 'अपने officially recognized industrial safety certifications देखें',
    'certs.search_placeholder': 'Course या ID से search करें...',
    'certs.filter_all': 'सभी स्थिति',
    'certs.filter_valid': 'Valid',
    'certs.filter_expired': 'Expired',
    'certs.filter_revoked': 'Revoked',
    'certs.loading': 'Certificates load हो रहे हैं...',
    'certs.empty_title': 'अभी कोई Certificate नहीं',
    'certs.empty_desc': 'अभी तक कोई training assessment complete नहीं हुई. Certificate पाने के लिए कोई course पूरा करें.',
    'certs.browse': 'Courses देखें',
    'certs.action_view': 'देखें',
    'certs.action_pdf': 'PDF',
    'certs.action_share': 'शेयर',
    'certs.share_linkedin': 'LinkedIn',
    'certs.share_whatsapp': 'WhatsApp',
    'certs.share_x': 'X (Twitter)',
    'certs.issued': 'जारी',
    'certs.expires': 'समाप्त',
    'certs.next_unlock': 'अगला Certificate',
    'certs.next_unlock_desc': 'ज़्यादा certificates पाने के लिए active modules पूरे करें',

    'features.badge': 'PLATFORM FEATURES',
    'features.title_prefix': 'वह सब कुछ जो चाहिए',
    'features.title_highlight': 'Workforce Upskill करने के लिए',
    'feature.chatbot.title': 'AI Chatbot',
    'feature.chatbot.description': 'Safety, SOPs, और compliance पर instant guidance पाने के लिए 24/7 available AI assistant.',
    'feature.quiz.title': 'AI Quiz Generator',
    'feature.quiz.description': 'हर training module के लिए adaptive difficulty और automatic scoring के साथ quizzes बनाएं.',
    'feature.training.title': 'Interactive Training',
    'feature.training.description': 'Video lessons, PDF study material, और clear learning path के साथ industrial training deliver करें.',
    'feature.certificate.title': 'Smart Certificates',
    'feature.certificate.description': 'Course complete होते ही unique QR code वाले digital certificates automatically generate करें.',
    'feature.analytics.title': 'Live Analytics',
    'feature.analytics.description': 'Compliance scores, course completion, और department performance को real time में track करें.',
    'feature.admin.title': 'Admin Dashboard',
    'feature.admin.description': 'Onboarding, course assignment, compliance tracking, और report export एक ही जगह manage करें.',

    'domains.badge': 'TRAINING DOMAINS',
    'domains.title': 'पूरा Industrial Coverage',
    'domains.description': 'Chemical safety से machine operations तक हर domain जो workforce को safe और compliant रखे.',
    'domains.course_single': 'Course',
    'domains.course_plural': 'Courses',
    'domains.explore': 'Courses Explore करें ->',
    'domain.health-safety': 'Health and Safety',
    'domain.machine-ops': 'Machine Operations',
    'domain.quality-compliance': 'Quality and Compliance',
    'domain.chemical-handling': 'Chemical Handling',
    'domain.electrical-safety': 'Electrical Safety',
    'domain.leadership-sops': 'Leadership and SOPs',

    'faq.badge': 'FAQ',
    'faq.title': 'Frequently Asked Questions',
    'faq.subtitle': 'शुरू करने से पहले जो जानना जरूरी है',
    'faq.q1': 'क्या platform free है use करने के लिए?',
    'faq.a1': 'हां. Free tier में core training courses, AI quizzes, और basic certificates मिलते हैं. Advanced organizational features higher plans पर available हैं. शुरू करने के लिए credit card की जरूरत नहीं है.',
    'faq.q2': 'यह platform किन industries और domains को cover करता है?',
    'faq.a2': 'यह platform Health and Safety, Machine Operations, Quality and Compliance, Chemical Handling, Electrical Safety, और Leadership and SOPs को Indian industrial और manufacturing environments के लिए cover करता है.',
    'faq.q3': 'Course complete होने के बाद certificate कैसे मिलता है?',
    'faq.a3': 'Passing quiz score और completed course के बाद unique ID, QR verification, trainee name, course name, score, और completion date वाला digital certificate automatically generate हो जाता है.',
    'faq.q4': 'क्या यह platform factory floor workers के लिए mobile friendly है?',
    'faq.a4': 'हां. यह platform mobile, tablet, और desktop पर fully responsive है, इसलिए workers किसी भी device से सीख सकते हैं, quiz दे सकते हैं, और certificates देख सकते हैं.',
    'faq.q5': 'AI chatbot कैसे काम करता है?',
    'faq.a5': 'Buddy AI industrial safety protocols, SOPs, और best practices पर trained है. Workers English या Hinglish में सवाल पूछकर instant guidance ले सकते हैं.',
    'faq.q6': 'क्या मैं KarmaSetu को अपनी पूरी organization के लिए use कर सकता हूं?',
    'faq.a6': 'हां. Enterprise plans में admin dashboards, workforce progress tracking, compliance reporting, custom courses, और dedicated support शामिल हैं.',
    'faq.q7': 'कौन सी languages supported हैं?',
    'faq.a7': 'KarmaSetu पूरे learning platform और Buddy AI assistant में English और Hinglish support करता है.',

    'blog.badge': 'FROM THE BLOG',
    'blog.title_prefix': 'Latest',
    'blog.title_highlight': 'Insights',
    'blog.view_all': 'सभी Articles देखें ->',

    'cta.title_prefix': 'तैयार हैं अपनी',
    'cta.title_highlight': 'Safety Training Upgrade करने के लिए?',
    'cta.description': 'India की industries KarmaSetu के AI-powered platform के साथ अपनी workforce training upgrade कर रही हैं.',
    'cta.primary': 'Free में Start करें',
    'cta.secondary': 'Features Explore करें ->',
    'cta.trust': 'Forever free plan | Credit card की जरूरत नहीं | 5 minute setup',

    'landing.mascot.label': 'Buddy AI',
    'landing.mascot.body': 'Industrial safety master करने के लिए ready हैं? मैं courses में step by step guide करूंगा.',
    'landing.mascot.cta': 'Training Start करने के लिए Sign In करें',
  },
};

interface LanguageContextType {
  language: Lang;
  setLanguage: (lang: Lang) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  language: 'EN',
  setLanguage: () => {},
  t: (key) => key,
});

export const useLanguage = () => useContext(LanguageContext);

export function LanguageProvider({ children }: { children: React.ReactNode }) {  const [language, setLang] = useState<Lang>('EN');

  React.useEffect(() => {
    const saved = localStorage.getItem('ks_language');
    if (saved === 'EN' || saved === 'HINGLISH') {
      setLang(saved);
    }
  }, []);

  const setLanguage = useCallback((lang: Lang) => {
    setLang(lang);
    localStorage.setItem('ks_language', lang);
  }, []);

  const t = useCallback((key: string) => {
    if (!translations[language]) return key;
    return translations[language][key] || key;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}
